/**
 * The widget's words, in the site's language (the « Langue » of its row in basedb). French
 * is the source and the key, as in the inbox; a sentence without a translation reads in
 * French.
 */

type Values = Readonly<Record<string, string | number>>

const EN: Readonly<Record<string, string>> = {
  'Ouvrir la conversation': 'Open the conversation',
  'Fermer la conversation': 'Close the conversation',
  'Assistant IA': 'AI assistant',
  'L’assistant répond tout de suite': 'The assistant answers right away',
  'Un conseiller vous répond': 'An advisor is answering you',
  'Nos conseillers répondent en quelques minutes': 'Our advisors answer within minutes',
  'Conseillers de retour {when}': 'Advisors back {when}',
  'Conseillers absents pour le moment': 'Advisors away for now',
  'Écrivez votre message…': 'Write your message…',
  Envoyer: 'Send',
  'Réponse générée par une IA': 'Answer generated by AI',
  '{name} a rejoint la conversation': '{name} joined the conversation',
  'Un conseiller a rejoint la conversation': 'An advisor joined the conversation',
  'Un conseiller va reprendre votre demande': 'An advisor will take over your request',
  'Conversation terminée': 'Conversation closed',
  'Propulsé par {name}': 'Powered by {name}',
  'Le message n’est pas parti. Réessayez.': 'The message was not sent. Please try again.',
  'Trop de messages d’un coup : patientez un instant.':
    'Too many messages at once: please wait a moment.',
  'Bonjour ! Comment pouvons-nous vous aider ?': 'Hello! How can we help you?',
  'aujourd’hui à {time}': 'today at {time}',
  'demain à {time}': 'tomorrow at {time}',
  '{day} à {time}': '{day} at {time}',
}

let language = 'fr'

export function setLanguage(code: string): void {
  language = code
}

export const locale = (): string => language

export function t(french: string, values?: Values): string {
  const text = (language === 'en' ? EN[french] : undefined) ?? french
  return values
    ? text.replace(/\{(\w+)\}/g, (all, name: string) => String(values[name] ?? all))
    : text
}

/** « lundi à 09:00 », « demain à 09:00 » — when the advisors are back. */
export function when(iso: string, now = new Date()): string {
  const at = new Date(iso)
  const time = new Intl.DateTimeFormat(language, { hour: '2-digit', minute: '2-digit' }).format(at)
  const days = Math.round(
    (new Date(at.getFullYear(), at.getMonth(), at.getDate()).getTime() -
      new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()) /
      86_400_000,
  )
  if (days <= 0) return t('aujourd’hui à {time}', { time })
  if (days === 1) return t('demain à {time}', { time })
  const day = new Intl.DateTimeFormat(language, { weekday: 'long' }).format(at)
  return t('{day} à {time}', { day, time })
}

export function clock(iso: string): string {
  return new Intl.DateTimeFormat(language, { hour: '2-digit', minute: '2-digit' }).format(
    new Date(iso),
  )
}
