/**
 * The widget's words, in the site's language (the « Langue » of its row of « Sites »). French
 * is the source and the key, as in the inbox; a sentence without a translation reads in
 * French.
 */

type Values = Readonly<Record<string, string | number>>

const EN: Readonly<Record<string, string>> = {
  'Ouvrir la conversation': 'Open the conversation',
  'Fermer la conversation': 'Close the conversation',
  'Assistant IA': 'AI assistant',
  Assistant: 'Assistant',
  'Bonjour {name}': 'Hello {name}',
  'Comment pouvons-nous vous aider ?': 'How can we help you?',
  'Notre assistant IA répond tout de suite. Un conseiller prend le relais si besoin.':
    'Our AI assistant answers right away. An advisor takes over when needed.',
  'Questions fréquentes': 'Frequent questions',
  'En train d’écrire…': 'Typing…',
  Masquer: 'Dismiss',
  'L’assistant répond tout de suite': 'The assistant answers right away',
  'Un conseiller vous répond': 'An advisor is answering you',
  'Nos conseillers répondent en quelques minutes': 'Our advisors answer within minutes',
  'Conseillers de retour {when}': 'Advisors back {when}',
  'Conseillers absents pour le moment': 'Advisors away for now',
  'Écrivez votre message…': 'Write your message…',
  Envoyer: 'Send',
  'Réponse générée par une IA': 'Answer generated by AI',
  '{name} a rejoint la conversation': '{name} joined the conversation',
  'Un conseiller a rejoint la conversation': 'An advisor joined the conversation',
  'Un conseiller va reprendre votre demande': 'An advisor will take over your request',
  'Conversation terminée': 'Conversation closed',
  'Ce message a été supprimé': 'This message was deleted',
  'Propulsé par {name}': 'Powered by {name}',
  'Le message n’est pas parti. Réessayez.': 'The message was not sent. Please try again.',
  'Trop de messages d’un coup : patientez un instant.':
    'Too many messages at once: please wait a moment.',
  'Bonjour ! Comment pouvons-nous vous aider ?': 'Hello! How can we help you?',
  'Joindre un fichier': 'Attach a file',
  Emoji: 'Emoji',
  'Retirer {name}': 'Remove {name}',
  'Déposez vos fichiers ici': 'Drop your files here',
  'Fichier refusé : images, PDF ou documents, 10 Mo au plus.':
    'File refused: images, PDF or documents, 10 MB at most.',
  'Cinq fichiers au plus par message.': 'Five files at most per message.',
  'Ouvrir {name}': 'Open {name}',
  'aujourd’hui à {time}': 'today at {time}',
  'demain à {time}': 'tomorrow at {time}',
  '{day} à {time}': '{day} at {time}',
  'Personne ne peut vous répondre tout de suite. Laissez votre e-mail : nous vous répondrons dès que possible.':
    'Nobody can answer you right now. Leave your e-mail: we will get back to you as soon as possible.',
  'votre@adresse.fr': 'you@example.com',
  'Votre adresse e-mail': 'Your e-mail address',
  'Cette adresse ne semble pas valable.': 'This address does not look valid.',
  'Merci ! Nous vous répondrons à {email}.': 'Thank you! We will answer you at {email}.',
  'L’assistant propose : {label}': 'The assistant suggests: {label}',
  'Non merci': 'No thanks',
  Accepter: 'Accept',
  '{label} : fait': '{label}: done',
  '{label} : refusé': '{label}: declined',
  '{label} : n’a pas pu être fait': '{label}: could not be done',
  '{label}…': '{label}…',
  'Comment s’est passée cette conversation ?': 'How did this conversation go?',
  'Recommanderiez-vous {site} à un proche ?': 'Would you recommend {site} to a friend?',
  'Votre note, de {min} à {max}': 'Your score, from {min} to {max}',
  'Très insatisfait': 'Very dissatisfied',
  Insatisfait: 'Dissatisfied',
  'Moyennement satisfait': 'Neutral',
  Satisfait: 'Satisfied',
  'Très satisfait': 'Very satisfied',
  'Pas du tout': 'Not at all likely',
  'Tout à fait': 'Extremely likely',
  'Un mot sur votre note ? (facultatif)': 'A word about your score? (optional)',
  'Votre commentaire': 'Your comment',
  'Envoyer ma note': 'Send my score',
  'Votre note n’est pas partie. Réessayez.': 'Your score was not sent. Please try again.',
  'Merci pour votre note : {score} sur {max}.': 'Thank you for your score: {score} out of {max}.',
}

let language = 'fr'

export function setLanguage(code: string): void {
  language = code
}

export const locale = (): string => language

export function t(french: string, values?: Values): string {
  const text = (language === 'en' ? EN[french] : undefined) ?? french
  return values
    ? text.replace(/\{(\w+)\}/g, (all, name: string) => String(values[name] ?? all))
    : text
}

/** « lundi à 09:00 », « demain à 09:00 » — when the advisors are back. */
export function when(iso: string, now = new Date()): string {
  const at = new Date(iso)
  const time = new Intl.DateTimeFormat(language, { hour: '2-digit', minute: '2-digit' }).format(at)
  const days = Math.round(
    (new Date(at.getFullYear(), at.getMonth(), at.getDate()).getTime() -
      new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()) /
      86_400_000,
  )
  if (days <= 0) return t('aujourd’hui à {time}', { time })
  if (days === 1) return t('demain à {time}', { time })
  const day = new Intl.DateTimeFormat(language, { weekday: 'long' }).format(at)
  return t('{day} à {time}', { day, time })
}

export function clock(iso: string): string {
  return new Intl.DateTimeFormat(language, { hour: '2-digit', minute: '2-digit' }).format(
    new Date(iso),
  )
}
