import { $t } from '@/lib/i18n'
import {
  Angry,
  Archive,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Award,
  Ban,
  Banknote,
  Battery,
  Bell,
  BellOff,
  Bookmark,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CheckCheck,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDashed,
  CircleDollarSign,
  CircleDot,
  CircleHelp,
  CirclePause,
  CirclePlay,
  CircleStop,
  CircleUser,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  Code,
  Coffee,
  Cpu,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Droplet,
  Euro,
  Eye,
  EyeOff,
  File,
  FileCheck,
  FileText,
  Filter,
  Fingerprint,
  Flag,
  FlagTriangleRight,
  Flame,
  Folder,
  Frown,
  Funnel,
  Gem,
  Gift,
  Globe,
  Hammer,
  Handshake,
  HardDrive,
  Hash,
  Heart,
  Hourglass,
  House,
  Image,
  Inbox,
  Info,
  Key,
  Laugh,
  Leaf,
  Lightbulb,
  Link,
  ListChecks,
  ListTodo,
  Loader,
  Lock,
  LockOpen,
  type LucideIcon,
  Mail,
  MapPin,
  Medal,
  Megaphone,
  Meh,
  MessageSquare,
  Minus,
  Monitor,
  Moon,
  Music,
  OctagonAlert,
  Package,
  Paperclip,
  Pause,
  Pencil,
  Percent,
  Phone,
  Pin,
  PinOff,
  Play,
  Plug,
  Plus,
  Power,
  Printer,
  Receipt,
  RefreshCw,
  Rocket,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Siren,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Square,
  Star,
  Sticker,
  Sun,
  Tag,
  Tags,
  Target,
  Terminal,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  User,
  UserCheck,
  Users,
  Wallet,
  Wand,
  Wifi,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

/**
 * The pictograms a thing may carry — basedb's set (`lib/option-icons.ts`), as it is: an
 * inbox dressed here reads the same names as an option or a table dressed in basedb.
 *
 * A curated set and not the whole library: importing every icon by name would put
 * thousands of them in the bundle for the sake of a picker, and `DynamicIcon` would turn
 * each into a chunk of its own. What is stored is the kebab-case NAME — the library's own —
 * so a list pasted from elsewhere keeps working, and a name this set does not know simply
 * shows no pictogram rather than failing.
 *
 * The labels are French and double as search terms: someone looking for « urgent » finds
 * the flame, and does not have to know it is called `flame`.
 */
export interface OptionIcon {
  readonly name: string
  readonly label: string
  readonly Icon: LucideIcon
}

export const OPTION_ICONS: readonly OptionIcon[] = [
  { name: 'circle', label: $t('Cercle'), Icon: Circle },
  { name: 'circle-check', label: $t('Validé'), Icon: CircleCheck },
  { name: 'circle-x', label: $t('Refusé'), Icon: CircleX },
  { name: 'circle-alert', label: $t('Alerte'), Icon: CircleAlert },
  { name: 'circle-help', label: $t('Question'), Icon: CircleHelp },
  { name: 'circle-dot', label: $t('Point'), Icon: CircleDot },
  { name: 'circle-dashed', label: $t('Pointillé'), Icon: CircleDashed },
  { name: 'circle-pause', label: $t('En pause'), Icon: CirclePause },
  { name: 'circle-play', label: $t('Démarré'), Icon: CirclePlay },
  { name: 'circle-stop', label: $t('Arrêté'), Icon: CircleStop },
  { name: 'circle-dollar-sign', label: $t('Facturation'), Icon: CircleDollarSign },
  { name: 'circle-user', label: $t('Profil'), Icon: CircleUser },
  { name: 'check', label: $t('Coche'), Icon: Check },
  { name: 'check-check', label: $t('Double coche'), Icon: CheckCheck },
  { name: 'x', label: $t('Croix'), Icon: X },
  { name: 'plus', label: $t('Plus'), Icon: Plus },
  { name: 'minus', label: $t('Moins'), Icon: Minus },
  { name: 'clock', label: $t('Horloge'), Icon: Clock },
  { name: 'hourglass', label: $t('Sablier attente'), Icon: Hourglass },
  { name: 'timer', label: $t('Minuteur'), Icon: Timer },
  { name: 'calendar', label: $t('Calendrier'), Icon: Calendar },
  { name: 'calendar-check', label: $t('Calendrier validé'), Icon: CalendarCheck },
  { name: 'calendar-clock', label: $t('Échéance'), Icon: CalendarClock },
  { name: 'flag', label: $t('Drapeau'), Icon: Flag },
  { name: 'bookmark', label: $t('Signet'), Icon: Bookmark },
  { name: 'star', label: $t('Étoile'), Icon: Star },
  { name: 'heart', label: $t('Cœur'), Icon: Heart },
  { name: 'flame', label: $t('Flamme urgent'), Icon: Flame },
  { name: 'zap', label: $t('Éclair rapide'), Icon: Zap },
  { name: 'bell', label: $t('Cloche notification'), Icon: Bell },
  { name: 'bell-off', label: $t('Cloche coupée'), Icon: BellOff },
  { name: 'triangle-alert', label: $t('Attention'), Icon: TriangleAlert },
  { name: 'octagon-alert', label: $t('Danger'), Icon: OctagonAlert },
  { name: 'info', label: $t('Information'), Icon: Info },
  { name: 'shield', label: $t('Bouclier'), Icon: Shield },
  { name: 'shield-check', label: $t('Sécurisé'), Icon: ShieldCheck },
  { name: 'shield-alert', label: $t('Risque'), Icon: ShieldAlert },
  { name: 'lock', label: $t('Verrouillé'), Icon: Lock },
  { name: 'lock-open', label: $t('Déverrouillé'), Icon: LockOpen },
  { name: 'eye', label: $t('Visible'), Icon: Eye },
  { name: 'eye-off', label: $t('Masqué'), Icon: EyeOff },
  { name: 'thumbs-up', label: $t('Pouce levé'), Icon: ThumbsUp },
  { name: 'thumbs-down', label: $t('Pouce baissé'), Icon: ThumbsDown },
  { name: 'smile', label: $t('Sourire content'), Icon: Smile },
  { name: 'frown', label: $t('Triste mécontent'), Icon: Frown },
  { name: 'meh', label: $t('Neutre'), Icon: Meh },
  { name: 'angry', label: $t('Colère'), Icon: Angry },
  { name: 'laugh', label: $t('Rire'), Icon: Laugh },
  { name: 'user', label: $t('Personne'), Icon: User },
  { name: 'users', label: $t('Équipe'), Icon: Users },
  { name: 'user-check', label: $t('Personne validée'), Icon: UserCheck },
  { name: 'building', label: $t('Entreprise'), Icon: Building },
  { name: 'building-2', label: $t('Immeuble'), Icon: Building2 },
  { name: 'briefcase', label: $t('Mallette'), Icon: Briefcase },
  { name: 'house', label: $t('Maison'), Icon: House },
  { name: 'mail', label: $t('Courrier email'), Icon: Mail },
  { name: 'phone', label: $t('Téléphone'), Icon: Phone },
  { name: 'message-square', label: $t('Message'), Icon: MessageSquare },
  { name: 'send', label: $t('Envoyé'), Icon: Send },
  { name: 'inbox', label: $t('Boîte de réception'), Icon: Inbox },
  { name: 'archive', label: $t('Archivé'), Icon: Archive },
  { name: 'trash-2', label: $t('Corbeille supprimé'), Icon: Trash2 },
  { name: 'pencil', label: $t('Crayon brouillon'), Icon: Pencil },
  { name: 'file', label: $t('Fichier'), Icon: File },
  { name: 'file-text', label: $t('Document'), Icon: FileText },
  { name: 'file-check', label: $t('Document validé'), Icon: FileCheck },
  { name: 'folder', label: $t('Dossier'), Icon: Folder },
  { name: 'tag', label: $t('Étiquette'), Icon: Tag },
  { name: 'tags', label: $t('Étiquettes'), Icon: Tags },
  { name: 'hash', label: $t('Dièse numéro'), Icon: Hash },
  { name: 'link', label: $t('Lien'), Icon: Link },
  { name: 'paperclip', label: $t('Pièce jointe'), Icon: Paperclip },
  { name: 'package', label: $t('Colis'), Icon: Package },
  { name: 'truck', label: $t('Livraison'), Icon: Truck },
  { name: 'shopping-cart', label: $t('Panier commande'), Icon: ShoppingCart },
  { name: 'credit-card', label: $t('Carte bancaire paiement'), Icon: CreditCard },
  { name: 'euro', label: $t('Euro'), Icon: Euro },
  { name: 'dollar-sign', label: $t('Dollar'), Icon: DollarSign },
  { name: 'banknote', label: $t('Billet'), Icon: Banknote },
  { name: 'wallet', label: $t('Portefeuille'), Icon: Wallet },
  { name: 'receipt', label: $t('Reçu facture'), Icon: Receipt },
  { name: 'percent', label: $t('Pourcentage remise'), Icon: Percent },
  { name: 'trending-up', label: $t('Hausse'), Icon: TrendingUp },
  { name: 'trending-down', label: $t('Baisse'), Icon: TrendingDown },
  { name: 'chart-line', label: $t('Courbe'), Icon: ChartLine },
  { name: 'chart-bar', label: $t('Histogramme'), Icon: ChartBar },
  { name: 'chart-pie', label: $t('Camembert'), Icon: ChartPie },
  { name: 'rocket', label: $t('Fusée lancement'), Icon: Rocket },
  { name: 'target', label: $t('Cible objectif'), Icon: Target },
  { name: 'trophy', label: $t('Trophée gagné'), Icon: Trophy },
  { name: 'crown', label: $t('Couronne'), Icon: Crown },
  { name: 'gift', label: $t('Cadeau'), Icon: Gift },
  { name: 'lightbulb', label: $t('Idée'), Icon: Lightbulb },
  { name: 'wrench', label: $t('Clé à molette outil'), Icon: Wrench },
  { name: 'settings', label: $t('Réglages||pictogramme d’engrenage'), Icon: Settings },
  { name: 'bug', label: $t('Bogue anomalie'), Icon: Bug },
  { name: 'code', label: $t('Code'), Icon: Code },
  { name: 'terminal', label: $t('Terminal'), Icon: Terminal },
  { name: 'database', label: $t('Base de données'), Icon: Database },
  { name: 'server', label: $t('Serveur'), Icon: Server },
  { name: 'cloud', label: $t('Nuage'), Icon: Cloud },
  { name: 'globe', label: $t('Monde'), Icon: Globe },
  { name: 'map-pin', label: $t('Lieu adresse'), Icon: MapPin },
  { name: 'sun', label: $t('Soleil'), Icon: Sun },
  { name: 'moon', label: $t('Lune'), Icon: Moon },
  { name: 'snowflake', label: $t('Flocon froid'), Icon: Snowflake },
  { name: 'leaf', label: $t('Feuille'), Icon: Leaf },
  { name: 'droplet', label: $t('Goutte'), Icon: Droplet },
  { name: 'coffee', label: $t('Café pause'), Icon: Coffee },
  { name: 'music', label: $t('Musique'), Icon: Music },
  { name: 'camera', label: $t('Appareil photo'), Icon: Camera },
  { name: 'image', label: $t('Image'), Icon: Image },
  { name: 'play', label: $t('Lecture'), Icon: Play },
  { name: 'pause', label: $t('Pause'), Icon: Pause },
  { name: 'square', label: $t('Carré'), Icon: Square },
  { name: 'ban', label: $t('Interdit'), Icon: Ban },
  { name: 'arrow-up', label: $t('Flèche haut'), Icon: ArrowUp },
  { name: 'arrow-down', label: $t('Flèche bas'), Icon: ArrowDown },
  { name: 'arrow-right', label: $t('Flèche droite'), Icon: ArrowRight },
  { name: 'refresh-cw', label: $t('Actualiser'), Icon: RefreshCw },
  { name: 'loader', label: $t('En cours'), Icon: Loader },
  { name: 'sparkles', label: $t('Nouveau'), Icon: Sparkles },
  { name: 'wand', label: $t('Baguette'), Icon: Wand },
  { name: 'sticker', label: $t('Autocollant'), Icon: Sticker },
  { name: 'award', label: $t('Récompense'), Icon: Award },
  { name: 'medal', label: $t('Médaille'), Icon: Medal },
  { name: 'gem', label: $t('Gemme'), Icon: Gem },
  { name: 'handshake', label: $t('Accord'), Icon: Handshake },
  { name: 'megaphone', label: $t('Annonce'), Icon: Megaphone },
  { name: 'siren', label: $t('Sirène urgence'), Icon: Siren },
  { name: 'hammer', label: $t('Marteau'), Icon: Hammer },
  { name: 'key', label: $t('Clé'), Icon: Key },
  { name: 'fingerprint', label: $t('Empreinte'), Icon: Fingerprint },
  { name: 'pin', label: $t('Épingle'), Icon: Pin },
  { name: 'pin-off', label: $t('Épingle retirée'), Icon: PinOff },
  { name: 'filter', label: $t('Filtre'), Icon: Filter },
  { name: 'funnel', label: $t('Entonnoir'), Icon: Funnel },
  { name: 'list-checks', label: $t('Liste de contrôle'), Icon: ListChecks },
  { name: 'list-todo', label: $t('À faire'), Icon: ListTodo },
  { name: 'clipboard-check', label: $t('Presse-papiers validé'), Icon: ClipboardCheck },
  { name: 'clipboard-list', label: $t('Presse-papiers'), Icon: ClipboardList },
  { name: 'search', label: $t('Recherche||pictogramme de loupe'), Icon: Search },
  { name: 'flag-triangle-right', label: $t('Fanion'), Icon: FlagTriangleRight },
  { name: 'thermometer', label: $t('Thermomètre'), Icon: Thermometer },
  { name: 'wifi', label: $t('Réseau'), Icon: Wifi },
  { name: 'battery', label: $t('Batterie'), Icon: Battery },
  { name: 'plug', label: $t('Prise'), Icon: Plug },
  { name: 'power', label: $t('Alimentation'), Icon: Power },
  { name: 'cpu', label: $t('Processeur'), Icon: Cpu },
  { name: 'hard-drive', label: $t('Disque'), Icon: HardDrive },
  { name: 'smartphone', label: $t('Mobile'), Icon: Smartphone },
  { name: 'monitor', label: $t('Écran'), Icon: Monitor },
  { name: 'printer', label: $t('Imprimante'), Icon: Printer },
]

const BY_NAME: ReadonlyMap<string, OptionIcon> = new Map(OPTION_ICONS.map((i) => [i.name, i]))

export function optionIcon(name: string | null | undefined): OptionIcon | undefined {
  return name === null || name === undefined ? undefined : BY_NAME.get(name)
}
